version: '3.8'

services:
  mongo:
    image: mongo
    container_name: items-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  items-api:
    build:
      context: ./apps/ItemMicroservice
      dockerfile: Dockerfile
    container_name: items-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo

volumes:
  mongo-data:
